services:
  api:
    build:
      context: ./api
      target: development
    restart: no
    environment:
      - ALLOWED_CORS_ORIGIN=${ALLOWED_CORS_ORIGIN:-http://localhost:5173}
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/app
      - /home/app/.venv

  web:
    build:
      context: ./web
      target: development
    image: dtnnr-web:dev
    pull_policy: build
    restart: no
    ports: !override
      - 5173:5173
    volumes:
      - ./web:/app
      - /app/node_modules
