# https://www.postgresql.org/docs/current/datatype-numeric.html

BIGINT_MAX = 9223372036854775807
INT_MAX = 2147483647
SMALLINT_MAX = 32767

MAX_PHONE_NUMBERS = INT_MAX
CONTACT_ID_MAX = BIGINT_MAX
ALLOCATOR_ID_MAX = BIGINT_MAX
OPERATOR_ID_MAX = BIGINT_MAX

HOST_ID_MAX = BIGINT_MAX
SANA_SCID_MAX = INT_MAX

NODE_ID_MAX = BIGINT_MAX
NODE_NUMBER_MAX = 2**32 - 1
SDR_WM_SIZE_MAX = BIGINT_MAX
HEAP_WORDS_MAX = BIGINT_MAX
WM_SIZE_MAX = BIGINT_MAX

BAND_ID_MAX = INT_MAX
BAND_FREQUENCY_MAX = BIGINT_MAX
UNDERLYING_COMMUNICATION_SERVICE_ID_MAX = INT_MAX
LINK_ID_MAX = BIGINT_MAX
DESTINATION_ID_MAX = BIGINT_MAX

SERVICE_NUMBER_MAX = BIGINT_MAX
GROUP_NUMBER_MAX = BIGINT_MAX
CL_PROTOCOL_ID_MAX = BIGINT_MAX
INDUCT_ID_MAX = BIGINT_MAX
PORT_NUMBER_MAX = 2**16 - 1
OUTDUCT_ID_MAX = INT_MAX
SEAT_ID_MAX = BIGINT_MAX
LK_RECORD_MAX = SMALLINT_MAX
