/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as OperatorsCreateRouteImport } from './routes/operators.create'
import { Route as OperatorsOperatorIdRouteImport } from './routes/operators.$operatorId'
import { Route as NodesCreateRouteImport } from './routes/nodes.create'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as HostsCreateRouteImport } from './routes/hosts.create'
import { Route as HostsHostIdRouteImport } from './routes/hosts.$hostId'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as AllocatorsCreateRouteImport } from './routes/allocators.create'
import { Route as AllocatorsAllocatorIdRouteImport } from './routes/allocators.$allocatorId'
import { Route as HomeOperatorsRouteImport } from './routes/_home.operators'
import { Route as HomeNodesRouteImport } from './routes/_home.nodes'
import { Route as HomeHostsRouteImport } from './routes/_home.hosts'
import { Route as HomeAllocatorsRouteImport } from './routes/_home.allocators'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsCreateRoute = OperatorsCreateRouteImport.update({
  id: '/operators/create',
  path: '/operators/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsOperatorIdRoute = OperatorsOperatorIdRouteImport.update({
  id: '/operators/$operatorId',
  path: '/operators/$operatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesCreateRoute = NodesCreateRouteImport.update({
  id: '/nodes/create',
  path: '/nodes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsCreateRoute = HostsCreateRouteImport.update({
  id: '/hosts/create',
  path: '/hosts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocatorsCreateRoute = AllocatorsCreateRouteImport.update({
  id: '/allocators/create',
  path: '/allocators/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocatorsAllocatorIdRoute = AllocatorsAllocatorIdRouteImport.update({
  id: '/allocators/$allocatorId',
  path: '/allocators/$allocatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOperatorsRoute = HomeOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNodesRoute = HomeNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => HomeRoute,
} as any)
const HomeHostsRoute = HomeHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAllocatorsRoute = HomeAllocatorsRouteImport.update({
  id: '/allocators',
  path: '/allocators',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeRouteWithChildren
  '/allocators': typeof HomeAllocatorsRoute
  '/hosts': typeof HomeHostsRoute
  '/nodes': typeof HomeNodesRoute
  '/operators': typeof HomeOperatorsRoute
  '/allocators/$allocatorId': typeof AllocatorsAllocatorIdRoute
  '/allocators/create': typeof AllocatorsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/create': typeof HostsCreateRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/create': typeof NodesCreateRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/operators/create': typeof OperatorsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeRouteWithChildren
  '/allocators': typeof HomeAllocatorsRoute
  '/hosts': typeof HomeHostsRoute
  '/nodes': typeof HomeNodesRoute
  '/operators': typeof HomeOperatorsRoute
  '/allocators/$allocatorId': typeof AllocatorsAllocatorIdRoute
  '/allocators/create': typeof AllocatorsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/create': typeof HostsCreateRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/create': typeof NodesCreateRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/operators/create': typeof OperatorsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_home/allocators': typeof HomeAllocatorsRoute
  '/_home/hosts': typeof HomeHostsRoute
  '/_home/nodes': typeof HomeNodesRoute
  '/_home/operators': typeof HomeOperatorsRoute
  '/allocators/$allocatorId': typeof AllocatorsAllocatorIdRoute
  '/allocators/create': typeof AllocatorsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/hosts/create': typeof HostsCreateRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/create': typeof NodesCreateRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/operators/create': typeof OperatorsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocators'
    | '/hosts'
    | '/nodes'
    | '/operators'
    | '/allocators/$allocatorId'
    | '/allocators/create'
    | '/contacts/$contactId'
    | '/hosts/$hostId'
    | '/hosts/create'
    | '/nodes/$nodeId'
    | '/nodes/create'
    | '/operators/$operatorId'
    | '/operators/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocators'
    | '/hosts'
    | '/nodes'
    | '/operators'
    | '/allocators/$allocatorId'
    | '/allocators/create'
    | '/contacts/$contactId'
    | '/hosts/$hostId'
    | '/hosts/create'
    | '/nodes/$nodeId'
    | '/nodes/create'
    | '/operators/$operatorId'
    | '/operators/create'
  id:
    | '__root__'
    | '/_home'
    | '/_home/allocators'
    | '/_home/hosts'
    | '/_home/nodes'
    | '/_home/operators'
    | '/allocators/$allocatorId'
    | '/allocators/create'
    | '/contacts/$contactId'
    | '/hosts/$hostId'
    | '/hosts/create'
    | '/nodes/$nodeId'
    | '/nodes/create'
    | '/operators/$operatorId'
    | '/operators/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  AllocatorsAllocatorIdRoute: typeof AllocatorsAllocatorIdRoute
  AllocatorsCreateRoute: typeof AllocatorsCreateRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  HostsHostIdRoute: typeof HostsHostIdRoute
  HostsCreateRoute: typeof HostsCreateRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  NodesCreateRoute: typeof NodesCreateRoute
  OperatorsOperatorIdRoute: typeof OperatorsOperatorIdRoute
  OperatorsCreateRoute: typeof OperatorsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/create': {
      id: '/operators/create'
      path: '/operators/create'
      fullPath: '/operators/create'
      preLoaderRoute: typeof OperatorsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$operatorId': {
      id: '/operators/$operatorId'
      path: '/operators/$operatorId'
      fullPath: '/operators/$operatorId'
      preLoaderRoute: typeof OperatorsOperatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/create': {
      id: '/nodes/create'
      path: '/nodes/create'
      fullPath: '/nodes/create'
      preLoaderRoute: typeof NodesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/create': {
      id: '/hosts/create'
      path: '/hosts/create'
      fullPath: '/hosts/create'
      preLoaderRoute: typeof HostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocators/create': {
      id: '/allocators/create'
      path: '/allocators/create'
      fullPath: '/allocators/create'
      preLoaderRoute: typeof AllocatorsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocators/$allocatorId': {
      id: '/allocators/$allocatorId'
      path: '/allocators/$allocatorId'
      fullPath: '/allocators/$allocatorId'
      preLoaderRoute: typeof AllocatorsAllocatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/operators': {
      id: '/_home/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof HomeOperatorsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/nodes': {
      id: '/_home/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof HomeNodesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/hosts': {
      id: '/_home/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HomeHostsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/allocators': {
      id: '/_home/allocators'
      path: '/allocators'
      fullPath: '/allocators'
      preLoaderRoute: typeof HomeAllocatorsRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAllocatorsRoute: typeof HomeAllocatorsRoute
  HomeHostsRoute: typeof HomeHostsRoute
  HomeNodesRoute: typeof HomeNodesRoute
  HomeOperatorsRoute: typeof HomeOperatorsRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAllocatorsRoute: HomeAllocatorsRoute,
  HomeHostsRoute: HomeHostsRoute,
  HomeNodesRoute: HomeNodesRoute,
  HomeOperatorsRoute: HomeOperatorsRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  AllocatorsAllocatorIdRoute: AllocatorsAllocatorIdRoute,
  AllocatorsCreateRoute: AllocatorsCreateRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  HostsHostIdRoute: HostsHostIdRoute,
  HostsCreateRoute: HostsCreateRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  NodesCreateRoute: NodesCreateRoute,
  OperatorsOperatorIdRoute: OperatorsOperatorIdRoute,
  OperatorsCreateRoute: OperatorsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
